var local = {
    name : "local",
    url : "http://127.0.0.1:5000/",
    login_button_selector : "",
    username_selector : "",
    password_selector : "",
    login_submit_selector : "",
    searches : {
    "static_cookies" : "http://127.0.0.1:5000/ecommerce",
    "static_bfp" : "http://127.0.0.1:5000/ecommerce/cookie=f&bfp=t",
    "static_newusers" : "http://127.0.0.1:5000/ecommerce/newuser=t",
    "dynamic_cookies" : "http://127.0.0.1:5000/ecommerce/price=d",
    "dynamic_bfp" : "http://127.0.0.1:5000/ecommerce/price=d&cookie=f&bfp=t",
    "dynamic_newusers" : "http://127.0.0.1:5000/ecommerce/price=d&newuser=t",
    "personalized_cookies" : "http://127.0.0.1:5000/ecommerce/price=p",
    "personalized_bfp" : "http://127.0.0.1:5000/ecommerce/price=p&cookie=f&bfp=t",
    "personalized_newusers" : "http://127.0.0.1:5000/ecommerce/price=p&newuser=t"
    },
};

var staples = {
    name : "staples",
    url : "http://www.staples.com/",
    login_button_selector : "A.login.loginBtnStyle.headerBtn",
    username_selector : "INPUT#username",
    password_selector : "INPUT#password",
    login_submit_selector : "A.buttonPrimaryAuto",
    searches : {
	"business+card" : "http://www.staples.com/business+card/directory_business+card?",
        "cabinet" : "http://www.staples.com/cabinet/directory_cabinet?",
        "red+folders" : "http://www.staples.com/red+folders/directory_red+folders?",
        "camcorders" : "http://www.staples.com/directory_camcorders/directory_camcorders?",
        "tools" : "http://www.staples.com/tools/directory_tools?",
        "coffee+maker" : "http://www.staples.com/coffee+maker/directory_coffee+maker?",
        "hard+drive" : "http://www.staples.com/hard+drive/directory_hard+drive?",
        "pads" : "http://www.staples.com/pads/directory_pads?",
        "desk+lamp" : "http://www.staples.com/desk+lamp/directory_desk+lamp?",
        "interactive+whiteboard" : "http://www.staples.com/interactive_whiteboard/directory_interactive+whiteboard?",
        "Photo+Paper" : "http://www.staples.com/Photo+Paper/directory_Photo+Paper?",
        "Post-it" : "http://www.staples.com/Post-it/directory_Post-it?",
        "Notebooks" : "http://www.staples.com/Notebooks/directory_Notebooks?",
        "Letter+opener" : "http://www.staples.com/Letter+opener/directory_Letter+opener?",
        "DuctTape" : "http://www.staples.com/Duct+Tape/directory_DuctTape?",
        "Stamps" : "http://www.staples.com/Stamps/directory_Stamps?",
        "Desk+Accessories" : "http://www.staples.com/Desk+Accessories/directory_Desk+Accessories?",
        "boxes" : "http://www.staples.com/Boxes/directory_boxes?",
        "Glue" : "http://www.staples.com/Glue/directory_Glue?",
	"Name+Labels" : "http://www.staples.com/Name+Labels/directory_Name+Labels?",
    },
};

var walmart = {
    name : "walmart",
    url : "http://www.walmart.com/cp/All-Departments/121828",
    login_button_selector : "p.unknownCustomerContent a:nth-child(2)",
    username_selector : "input.CreateAcctForm:nth-child(3)",
    password_selector : "input.CreateAcctForm:nth-child(5)",
    login_submit_selector : ".SignInBtn",
    searches : {
	"cook+ware" : "http://www.walmart.com/search/search-ng.do?search_query=cook+ware",
        "chairs" : "http://www.walmart.com/search/search-ng.do?search_query=chairs",
        "pillows" : "http://www.walmart.com/search/search-ng.do?search_query=pillows",
        "Bathroom+Accessories" : "http://www.walmart.com/search/search-ng.do?search_query=Bathroom+Accessories",
        "art+supplies" : "http://www.walmart.com/search/search-ng.do?search_query=art+supplies",
        "lamps" : "http://www.walmart.com/search/search-ng.do?search_query=lamps",
        "drills" : "http://www.walmart.com/search/search-ng.do?search_query=drills",
        "vases" : "http://www.walmart.com/search/search-ng.do?search_query=vases",
        "clocks" : "http://www.walmart.com/search/search-ng.do?search_query=clocks",
	"area+rugs" : "http://www.walmart.com/search/search-ng.do?search_query=area+rugs",
        "woman+pants" : "http://www.walmart.com/search/search-ng.do?search_query=woman+pants",
        "scarfs" : "http://www.walmart.com/search/search-ng.do?search_query=scarfs",
	"sunglasses" : "http://www.walmart.com/search/search-ng.do?search_query=sunglasses",
        "boots" : "http://www.walmart.com/search/search-ng.do?search_query=boots",
        "man+shirts" : "http://www.walmart.com/search/search-ng.do?search_query=man+shirts",
	"strollers" : "http://www.walmart.com/search/search-ng.do?search_query=strollers",
        "diapers" : "http://www.walmart.com/search/search-ng.do?search_query=diapers",
        "toddler+beds" : "http://www.walmart.com/search/search-ng.do?search_query=toddler+beds",
        "infant+car+seats" : "http://www.walmart.com/search/search-ng.do?search_query=infant+car+seats",
        "baby+shower+gifts" : "http://www.walmart.com/search/search-ng.do?search_query=baby+shower+gifts"
    },
};

var officedepot = {
    name : "officedepot",
    url : "http://www.officedepot.com/",
    login_button_selector : "A.accountLogin",
    username_selector : "#loginContentBody > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(1) > span:nth-child(2) > input:nth-child(1)",
    password_selector : "#loginContentBody > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(2) > span:nth-child(2) > input:nth-child(1)",
    login_submit_selector : "#loginContentBody > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > form:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > input:nth-child(1)",
    dont_check_url : true,
    searches : {
	"business+card" : "http://www.officedepot.com/catalog/search.do?Ntt=business+card",
        "cabinet" : "http://www.officedepot.com/catalog/search.do?Ntt=cabinet",
        "red+folders" : "http://www.officedepot.com/catalog/search.do?Ntt=red+folders",
        "camcorders" : "http://www.officedepot.com/catalog/search.do?Ntt=camcorders",
        "tools" : "http://www.officedepot.com/catalog/search.do?Ntt=tools",
        "coffee+maker" : "http://www.officedepot.com/catalog/search.do?Ntt=coffee+maker",
        "pads" : "http://www.officedepot.com/catalog/search.do?Ntt=pads",
        "desk+lamp" : "http://www.officedepot.com/catalog/search.do?Ntt=desk+lamp",
        "interactive+whiteboard" : "http://www.officedepot.com/catalog/search.do?Ntt=interactive+whiteboard",
        "notebooks" : "http://www.officedepot.com/catalog/search.do?Ntt=notebooks",
        "Photo+Paper" : "http://www.officedepot.com/catalog/search.do?Ntt=Photo+Paper",
        "Post-it" : "http://www.officedepot.com/catalog/search.do?Ntt=Post-it",
        "letter+opener" : "http://www.officedepot.com/catalog/search.do?Ntt=letter+opener",
        "Duct+Tape" : "http://www.officedepot.com/catalog/search.do?Ntt=Duct+Tape",
        "Stamps" : "http://www.officedepot.com/catalog/search.do?Ntt=Stamps",
        "Desk+Accessories" : "http://www.officedepot.com/catalog/search.do?Ntt=Desk+Accessories",
        "boxes" : "http://www.officedepot.com/catalog/search.do?Ntt=boxes",
        "Glue" : "http://www.officedepot.com/catalog/search.do?Ntt=Glue",
        "Name+Labels" : "http://www.officedepot.com/catalog/search.do?Ntt=Name+Labels",
        "hard+drive" : "http://www.officedepot.com/catalog/search.do?Ntt=hard+drive",
    },
};

var sears = {
    name : "sears",
    url : "http://www.sears.com/",
    login_button_selector : "a#signInLink",
    framebust : true,
    frame_id : 'easyXDM_default6377_provider',
    username_selector : "#email",
    password_selector : "#password",
    login_submit_selector : ".signIn",
    dont_check_url : true,
    searches : {
	"chairs" : "http://www.sears.com/search=chairs",
        "cook+ware" : "http://www.sears.com/search=cook+ware",
        "pillows" : "http://www.sears.com/search=pillows",
        "bathroom+accessories" : "http://www.sears.com/search=bathroom+accessories",
        "art+supplies" : "http://www.sears.com/search=art+supplies",
        "lamps" : "http://www.sears.com/search=lamps",
        "drills" : "http://www.sears.com/search=drills",
        "vases" : "http://www.sears.com/search=vases",
        "clocks" : "http://www.sears.com/search=clocks",
        "area+rugs" : "http://www.sears.com/search=area+rugs",
        "woman+pants" : "http://www.sears.com/search=woman+pants",
        "scarfs" : "http://www.sears.com/search=scarfs",
        "sunglasses" : "http://www.sears.com/search=sunglasses",
        "boots" : "http://www.sears.com/search=boots",
        "man+shirts" : "http://www.sears.com/search=man+shirts",
        "stroller" : "http://www.sears.com/search=stroller",
        "diapers" : "http://www.sears.com/search=diapers",
        "toddler+beds" : "http://www.sears.com/search=toddler+beds",
        "infant+car+seats" : "http://www.sears.com/search=infant+car+seats",
        "baby+shower+gifts" : "http://www.sears.com/search=baby+shower+gifts"
    },
};

var cdw = {
    name : "cdw",
    url : "http://www.cdw.com/",
    login_button_selector : "#log-on-link > strong:nth-child(1)",
    username_selector : "#gh_username",
    password_selector : "#gh_password",
    login_submit_selector : ".logonBtn",
    searches : {
	"batteries" : "http://www.cdw.com/shop/search/result.aspx?key=batteries",
        "copy+machines" : "http://www.cdw.com/shop/search/result.aspx?key=copy+machines",
        "monitors+23" : "http://www.cdw.com/shop/search/result.aspx?key=monitors+23",
        "lcd+televisions" : "http://www.cdw.com/shop/search/result.aspx?key=lcd+televisions",
        "headphones" : "http://www.cdw.com/shop/search/result.aspx?key=headphones",
        "speakers" : "http://www.cdw.com/shop/search/result.aspx?key=speakers",
        "phones" : "http://www.cdw.com/shop/search/result.aspx?key=phones",
        "digital+cameras" : "http://www.cdw.com/shop/search/result.aspx?key=digital+cameras",
        "laser+printer" : "http://www.cdw.com/shop/search/result.aspx?key=laser+printer",
        "memory+cards" : "http://www.cdw.com/shop/search/result.aspx?key=memory+cards",
        "flash+drives" : "http://www.cdw.com/shop/search/result.aspx?key=flash+drives",
        "batteries" : "http://www.cdw.com/shop/search/result.aspx?key=batteries",
        "webcameras" : "http://www.cdw.com/shop/search/result.aspx?key=webcameras",
        "printer+color" : "http://www.cdw.com/shop/search/result.aspx?key=printer+color",
        "calculator" : "http://www.cdw.com/shop/search/result.aspx?key=calculator",
        "mouse" : "http://www.cdw.com/shop/search/result.aspx?key=mouse",
        "keyboard" : "http://www.cdw.com/shop/search/result.aspx?key=keyboard",
        "laptop+cases" : "http://www.cdw.com/shop/search/result.aspx?key=laptop+cases",
        "car+phone" : "http://www.cdw.com/shop/search/result.aspx?key=car+phone",
        "flashlights" : "http://www.cdw.com/shop/search/result.aspx?key=flashlights",
    },
};

var bestbuy = {
    name : "bestbuy",
    url : "http://www.bestbuy.com/",
    login_button_selector : "a.heavy:nth-child(1)",
    username_selector : "#TxtEmailId",
    password_selector : "#PwdPasswordId",
    login_submit_selector : "#SigninBTN",
    searches : {
	"controller" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=controller",
        "dashboard+mount" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=dashboard+mount",
        "stylus" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=stylus",
        "car+battery" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=car+battery",
        "alarm+clock" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=alarm+clock",
        "computer+bag" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=computer+bag",
        "bookcase" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=bookcase",
        "remote" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=remote",
        "wireless" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=wireless",
        "keyboard" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=keyboard",
        "lamp" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=lamp",
        "ethernet" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=ethernet",
        "tower" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=tower",
        "phone+case" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=phone+case",
        "hdmi+cabple" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=hdmi+cabple",
        "speakers" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=speakers",
        "surround+sound" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=surround+sound",
        "memory" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=memory",
        "cd" : "http://www.bestbuy.com/site/searchpage.jsp?_dyncharset=ISO-8859-1&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=15&sp=&qp=&list=n&iht=y&usc=All+Categories&ks=960&saas=saas&st=cd"
    },
};

var newegg = {
    name : "newegg",
    url : "http://www.newegg.com/",
    login_button_selector : "li.top-tab:nth-child(2) > a:nth-child(2)",
    username_selector : "#UserName",
    password_selector : "#UserPwd",
    login_submit_selector : "#submit",
    searches : {
	"monitors+23" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=monitors+23",
        "lcd+televisions" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=lcd+televisions",
        "headphones" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=headphones",
        "speakers" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=speakers",
        "phones" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=phones",
        "waterproof+digital+cameras" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=waterproof+digital+cameras",
        "laser+printer" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=laser+printer",
        "copy+machine" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=copy+machine",
        "memory+cards" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=memory+cards",
        "flash+drives" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=flash+drives",
        "batteries" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=batteries",
        "web+cameras" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=web+cameras",
        "printer+color" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=printer+color",
        "e-book" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=e-book",
        "calculator" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=calculator",
        "mouse" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=mouse",
        "keyboard" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=keyboard",
        "laptop+cases" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=laptop+cases",
        "flashlights" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=flashlights",
        "car+phone" : "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Order=BESTMATCH&N=-1&isNodeId=1&Description=car+phone",
    },
};

var macys = {
    name : "macys",
    url : "http://www.macys.com/",
    login_button_selector : "#globalMastheadSignIn",
    username_selector : "#email",
    password_selector : "#password",
    login_submit_selector : "#accountSignIn",
    searches : {
	"ties" : "http://www1.macys.com/shop/search?keyword=ties",
        "coats" : "http://www1.macys.com/shop/search?keyword=coats",
        "boots" : "http://www1.macys.com/shop/search?keyword=boots",
        "fur" : "http://www1.macys.com/shop/search?keyword=fur",
        "suits" : "http://www1.macys.com/shop/search?keyword=suits",
        "slippers" : "http://www1.macys.com/shop/search?keyword=slippers",
        "pajamas" : "http://www1.macys.com/shop/search?keyword=pajamas",
        "hats" : "http://www1.macys.com/shop/search?keyword=hats",
        "sundress" : "http://www1.macys.com/shop/search?keyword=sundress",
        "necklace" : "http://www1.macys.com/shop/search?keyword=necklace",
        "jeans" : "http://www1.macys.com/shop/search?keyword=jeans",
        "belts" : "http://www1.macys.com/shop/search?keyword=belts",
        "nailpolish" : "http://www1.macys.com/shop/search?keyword=nailpolish",
        "cufflinks" : "http://www1.macys.com/shop/search?keyword=cufflinks",
        "shorts" : "http://www1.macys.com/shop/search?keyword=shorts",
        "gloves" : "http://www1.macys.com/shop/search?keyword=gloves",
        "rings" : "http://www1.macys.com/shop/search?keyword=rings",
        "dishes" : "http://www1.macys.com/shop/search?keyword=dishes",
        "glasses" : "http://www1.macys.com/shop/search?keyword=glasses",
        "tea" : "http://www1.macys.com/shop/search?keyword=tea",
    },
};

var homedepot = {
    name : "homedepot",
    url : "http://www.homedepot.com/",
    login_button_selector : "#accountInfo > a:nth-child(1)",
    username_selector : "#email_id",
    password_selector : "#password",
    login_submit_selector : "#signIn",
    searches : {
	"flower+gardening" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=flower+gardening&selectedCatgry=Search+All",
        "gloves" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=gloves&selectedCatgry=Search+All",
        "duct+tape" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=duct+tape&selectedCatgry=Search+All",
        "rigid+insulation" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=rigid+insulation&selectedCatgry=Search+All",
        "wood" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=wood&selectedCatgry=Search+All",
        "frames" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=frames&selectedCatgry=Search+All",
        "paint+supplies" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=paint+supplies&selectedCatgry=Search+All",
        "sinks" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=sinks&selectedCatgry=Search+All",
        "toilet+seats" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=toilet+seats&selectedCatgry=Search+All",
        "lamps" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=lamps&selectedCatgry=Search+All",
        "chair" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=chair&selectedCatgry=Search+All",
        "cushions" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=cushions&selectedCatgry=Search+All",
        "shag+rugs" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=shag+rugs&selectedCatgry=Search+All",
        "ladders" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=ladders&selectedCatgry=Search+All",
        "led+bulbs" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=led+bulbs&selectedCatgry=Search+All",
        "front+doors" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=front+doors&selectedCatgry=Search+All",
        "bathroom+cabinets" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=bathroom+cabinets&selectedCatgry=Search+All",
        "drills" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=drills&selectedCatgry=Search+All",
        "bathroom+accessories" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=bathroom+accessories&selectedCatgry=Search+All",
        "woodworking+tools" : "http://www.homedepot.com/webapp/catalog/servlet/Search?storeId=10051&langId=-1&keyword=woodworking+tools&selectedCatgry=Search+All",
    },
};

var jcpenney = {
    name : "jcpenney",
    url : "http://www.jcpenney.com/",
    login_button_selector : "li.pipe:nth-child(5) > a:nth-child(1)",
    framebust : true,
    frame_id : 'modalIframe',
    username_selector : "#emailidLogin",
    password_selector : "#mypasswdLogin",
    login_submit_selector : "#loginSubmit",
    searches : {
	"cook+ware" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=cook+ware&ruleZoneName=XGNSZone",
        "pillows" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=pillows&ruleZoneName=XGNSZone",
        "bathroom+accessories" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=bathroom+accessories&ruleZoneName=XGNSZone",
        "art+supplies" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=art+supplies&ruleZoneName=XGNSZone",
        "lamps" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=lamps&ruleZoneName=XGNSZone",
        "drills" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=drills&ruleZoneName=XGNSZone",
        "vases" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=vases&ruleZoneName=XGNSZone",
        "clocks" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=clocks&ruleZoneName=XGNSZone",
        "area+rugs" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=area+rugs&ruleZoneName=XGNSZone",
        "woman+pants" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=woman+pants&ruleZoneName=XGNSZone",
        "scarfs" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=scarfs&ruleZoneName=XGNSZone",
        "purses" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=purses&ruleZoneName=XGNSZone",
        "baby+shower+gifts" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=baby+shower+gifts&ruleZoneName=XGNSZone",
        "sunglasses" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=sunglasses&ruleZoneName=XGNSZone",
        "boots" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=boots&ruleZoneName=XGNSZone",
        "man+shirts" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=man+shirts&ruleZoneName=XGNSZone",
        "stroller" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=stroller&ruleZoneName=XGNSZone",
        "diapers" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=diapers&ruleZoneName=XGNSZone",
        "toddler+beds" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=toddler+beds&ruleZoneName=XGNSZone",
        "infant+car+seats" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=infant+car+seats&ruleZoneName=XGNSZone",
        "chairs" : "http://www.jcpenney.com/dotcom/jsp/search/results.jsp?fromSearch=true&Ntt=chairs&ruleZoneName=XGNSZone"
    },
};

var store_list = ['local', 'homedepot', 'walmart'];//, 'officedepot', 'sears', 'cdw', 'bestbuy', 'newegg', 'macys', 'homedepot', 'jcpenney'];

var map = {
    'local': local,
    'staples': staples,
    'walmart': walmart,
    'officedepot' : officedepot,
    'sears' : sears,
    'cdw': cdw,
    'bestbuy': bestbuy,
    'newegg' : newegg,
    'macys' : macys,
    'homedepot' : homedepot,
    'jcpenney' : jcpenney,
};

exports.store_list = store_list;
exports.store_map = map;

